#cloud-config
# vim: syntax=yaml
#
# This is the configuration syntax that the write_files module
# will know how to understand. encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided. 
#
# Note: Content strings here are truncated for example purposes.
write_files:
- encoding: b64
  content: Y3VybCAtTG8ga29uZy4yLjQuMS5hbWQ2NC5kZWIgImh0dHBzOi8vZG93bmxvYWQua29uZ2hxLmNvbS9nYXRld2F5LTIueC11YnVudHUtJChsc2JfcmVsZWFzZSAtY3MpL3Bvb2wvYWxsL2sva29uZy9rb25nXzIuNC4xX2FtZDY0LmRlYiIKc3VkbyBkcGtnIC1pIGtvbmcuMi40LjEuYW1kNjQuZGViCgpzdWRvIGFwdCB1cGRhdGUKc3VkbyBhcHQgaW5zdGFsbCBwb3N0Z3Jlc3FsIHBvc3RncmVzcWwtY29udHJpYgpzdWRvIC91c3IvYmluL3Bvc3RncmVzcWwtc2V0dXAgLS1pbml0ZGIKc3VkbyBzeXN0ZW1jdGwgZW5hYmxlIHBvc3RncmVzcWwuc2VydmljZQpzdWRvIHN5c3RlbWN0bCBzdGFydCBwb3N0Z3Jlc3FsCgo=
  owner: root:root
  path: /tmp/selinux
  permissions: '0644'
#- content: |
    # My new /etc/sysconfig/samba file

#   SMBDOPTIONS="-D"
#  path: /tmp
#- content: !!binary |
#    f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAAwARAAAAAAABAAAAAAAAAAJAVAAAAAAAAAAAAAEAAOAAI
#    AEAAHgAdAAYAAAAFAAAAQAAAAAAAAABAAEAAAAAAAEAAQAAAAAAAwAEAAAAAAADAAQAAAAAAAAgA
#    AAAAAAAAAwAAAAQAAAAAAgAAAAAAAAACQAAAAAAAAAJAAAAAAAAcAAAAAAAAABwAAAAAAAAAAQAA
 #   ....
#  path: /tmp/arch
#  permissions: '0555'